# Site settings
author: Justin Beaulieu
title: My journey of development.
header-img: img/home-bg.png
email: beaulieudev@gmail.com
copyright_name: Justin Beaulieu
description: > # this means to ignore newlines until "baseurl:"
  Fresh mind ready to sculpt.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Beaulieu527

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
